#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="x86_64-linux"

echo "${YELLOW}Applying configuration...${NC}"
sudo nixos-rebuild switch --flake .#${SYSTEM_TYPE} $@

echo "${GREEN}Configuration applied!${NC}" 