#!/usr/bin/env bash
set -euo pipefail

GREEN=$'\e[1;32m'
YELLOW=$'\e[1;33m'
RED=$'\e[1;31m'
NC=$'\e[0m'

SYSTEM_TYPE="x86_64-linux"
FLAKE_SYSTEM="homeConfigurations.wsl2.${SYSTEM_TYPE}.activationPackage"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@

echo "${YELLOW}Switching to new generation...${NC}"
./result/activate

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
