#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="x86_64-linux"
FLAKE_SYSTEM="homeConfigurations.skagur.activationPackage"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Build completed successfully!${NC}"
