#!/usr/bin/env bash
set -euo pipefail

GREEN=$'\e[1;32m'
YELLOW=$'\e[1;33m'
RED=$'\e[1;31m'
NC=$'\e[0m'

echo "${YELLOW}Rolling back Linux configuration...${NC}"
home-manager rollback
echo "${GREEN}Rollback completed!${NC}" 